language: c
os:
    - linux
compiler:
    - gcc
script:
    - make all
    - make tests
deploy:
    provider: releases
        api_key:
            secure: 95f662f880b0857f8b2985a5b5115a278a8a1811
        file: *.out
        skip_cleanup: true
    on:
        tags: true
        branch: master
