language: c
os:
    - linux
compiler:
    - gcc
script:
    - make all
    - make tests
deploy:
    provider: releases
        api_key:
            secure: $gittok
        file: main.out
        skip_cleanup: true
    on:
        tags: true
